{
	"BaseType" : "UI.View",
	"Properties" : [{
        "Attributes" : "Serialized",
		"Name" : "Text",
		"Type" : "String",
		"Visibility" : "Public"
	}, {
        "Attributes" : "Serialized",
		"Name" : "TextAlign",
		"Type" : "Core.TextAlign",
		"Visibility" : "Public"
	}, {
        "Attributes" : "Serialized",
		"Name" : "TextWrapping",
		"Type" : "Core.TextWrapping",
		"Visibility" : "Public"
	}],
	"Namespace":"UI",
	"Type" : "Class"
}