Type: Class
Functions:
  - Name: Load
  - Name: Unload
Graphs:
  Function.Load:
    Nodes:
      - ID: Input
        Name: Input
      - ID: Output
        Name: Output
  Function.Unload:
    Nodes:
      - ID: Input
        Name: Input
      - ID: Output
        Name: Output
Namespace: System
Properties:
  - Attributes:
      - Serialize
    Name: Root
    Type: System.Path
  - Name: Extensions
    Type: Array<Extension<InterfaceType>>
TemplateTypes:
  - InterfaceType
