{
	"BaseType" : "UI.FlexBox",
	"Interfaces" : ["FieldEditor"],
	"Namespace" : "ClassGen",
	"Type" : "View",
	"Values" : {
		"Data" : [{

		}, {

		}],
		"Spacing" : 4.000000
	},
	"Views" : [{
		"BaseType" : "UI.TextButton",
		"Name" : "Button",
		"Values" : {
			"Text" : "Add"
		},
		"Variable" : true
	}, {
		"BaseType" : "UI.ListView",
		"Bindings" : {
			"CountItems" : "items.size()",
			"Item" : "provideViewForItem(*this, Index)"
		},
		"Name" : "List",
		"Variable" : true
	}]
}