Type: Class
BaseType: ECS.PostProcessStep
Functions:
  - InputParameters:
      - Copy: false
        Name: Scene
        Type: EScene
        Writable: true
      - Copy: false
        Name: RenderBuffer
        Type: Graphics.RenderBuffer
        Writable: false
    Name: Render
Graphs:
  Function.Render:
    Nodes:
      - ID: Input
        Name: Input
      - ID: Output
        Name: Output
Namespace: ECS
Values:
  Material:
    Type: GlowMaterial
