#pragma once

#include <ThirdParty.pch.hpp>

#include <Async/Task.hpp>
#include <Async/TaskManager.hpp>
#include <Containers/Array.hpp>
#include <Containers/ArrayUtils.hpp>
#include <Containers/Deque.hpp>
#include <Containers/List.hpp>
#include <Containers/Map.hpp>
#include <Containers/MapUtils.hpp>
#include <Containers/Queue.hpp>
#include <Containers/Set.hpp>
#include <Containers/SortedMap.hpp>
#include <Containers/SortedSet.hpp>
#include <Containers/Stack.hpp>
#include <Containers/StaticArray.hpp>
#include <DateTime/Counter.hpp>
#include <DateTime/Date.hpp>
#include <DateTime/Duration.hpp>
#include <DateTime/Stopwatch.hpp>
#include <DateTime/Time.hpp>
#include <DateTime/Timer.hpp>
#include <Debug/DebugUtils.hpp>
#include <Debug/Profiler.hpp>
#include <Image/Color.hpp>
#include <Math/Matrix.hpp>
#include <Math/Quaternion.hpp>
#include <Math/Ratio.hpp>
#include <Math/Vector.hpp>
#include <Memory/Allocation.hpp>
#include <Memory/Assets.hpp>
#include <Memory/Casts.hpp>
#include <Memory/InplaceStorage.hpp>
#include <Memory/References.hpp>
#include <Meta/Aliases.hpp>
#include <Meta/Flags.hpp>
#include <Meta/Inheritance.hpp>
#include <Meta/Substitution.hpp>
#include <Meta/TypeModifiers.hpp>
#include <Multithreading/Synchronization/Locks.hpp>
#include <Multithreading/Synchronization/Mutexes.hpp>
#include <Multithreading/Synchronization/Semaphore.hpp>
#include <Multithreading/SafeQueue.hpp>
#include <Multithreading/Thread.hpp>
#include <Multithreading/ThreadPool.hpp>
#include <Reflection/ClassReference.hpp>
#include <Reflection/MetaObject.hpp>
#include <Reflection/MetaObjectStorage.hpp>
#include <Reflection/DynamicSerialization.hpp>
#include <Serialization/Serialization.hpp>
#include <Serialization/Serializer.hpp>
#include <Serialization/Storage.hpp>
#include <System/CommandLine.hpp>
#include <System/ConfigFile.hpp>
#include <System/Domain.hpp>
#include <System/Filesystem.hpp>
#include <System/ResolutionMetrics.hpp>
#include <System/PackageIdentifier.hpp>
#include <System/Process.hpp>
#include <System/Version.hpp>
#include <Text/String.hpp>
#include <Text/StringUtils.hpp>
#include <Text/Unicode.hpp>

#include <System/ConfigFile.inl>
