{
    "Namespace" : "Math",
	"Attributes": ["Structure"],
	"Properties" : [{
		"Attributes" : "Serialized",
		"Name" : "Position",
		"Type" : "Math.Vector"
	}, {
		"Attributes" : "Serialized",
		"Name" : "Rotation",
		"Type" : "Math.Quaternion"
	}],
	"Type" : "Class",
	"Values" : {
		"Position" : {
			"W" : 0.000000,
			"X" : 0.000000,
			"Y" : 0.000000,
			"Z" : 0.000000
		},
		"Rotation" : {
			"W" : 0.000000,
			"X" : 0.000000,
			"Y" : 0.000000,
			"Z" : 0.000000
		}
	}
}