//CLASSGEN GENERATED REGION: Includes
#include "TreeWidget.gen.h"
#include <MetaObjectSerializationHelper.h>
//CLASSGEN END REGION

//CLASSGEN GENERATED REGION: Namespace
namespace UI
//CLASSGEN END REGION
//CLASSGEN GENERATED REGION: NamespaceBegin
{
//CLASSGEN END REGION


//CLASSGEN GENERATED REGION: NamespaceEnd
}
//CLASSGEN END REGION
