#pragma once

//CLASSGEN GENERATED REGION: Includes
//CLASSGEN END REGION
//CLASSGEN GENERATED REGION: NamespaceBegin
//CLASSGEN END REGION
//CLASSGEN GENERATED REGION: Source
using Boolean = bool;
//CLASSGEN END REGION
//CLASSGEN GENERATED REGION: NamespaceEnd
//CLASSGEN END REGION
