#pragma once

//CLASSGEN GENERATED REGION: Includes
//CLASSGEN END REGION
//CLASSGEN GENERATED REGION: NamespaceBegin
//CLASSGEN END REGION
//CLASSGEN GENERATED REGION: Source
using ByteInteger = unsigned char;
//CLASSGEN END REGION
//CLASSGEN GENERATED REGION: NamespaceEnd
//CLASSGEN END REGION
