#pragma once

//CLASSGEN GENERATED REGION: Includes
//CLASSGEN END REGION
//CLASSGEN GENERATED REGION: NamespaceBegin
//CLASSGEN END REGION
//CLASSGEN GENERATED REGION: Source
using Float = float;
//CLASSGEN END REGION
//CLASSGEN GENERATED REGION: NamespaceEnd
//CLASSGEN END REGION
