Type: Class
Attributes:
  - Structure
  - DefaultConstructor
  - Destructor
Namespace: Graphics
Properties:
  - Name: Data
    Type: InplaceStorage<TexturePrivateData, 8, 8>
  - Name: Buffer
    Type: Array<uint8_t>
  - Name: Size
    Type: hlslpp.int3
  - Name: Channels
    Type: uint8_t
  - Name: Filtration
    Type: Graphics.TextureFiltration
  - Name: Wrapping
    Type: Graphics.TextureWrapping
