Type: Material
PixelShader: D:/Projects/CMake/Sandbox/Sandbox/Assets/Test/TestMaterial.ps
Properties:
  - Name: Color
    UseInPixelShader: true
    UseInVertexShader: false
    Value:
      w: 1
      x: 2.1400001
      y: 1.23000002
      z: 0.389999986
  - Name: Speed
    UseInPixelShader: false
    UseInVertexShader: true
    Value:
      w: 0
      x: 0
      y: 0
      z: 0
  - Name: ImageOffset
    UseInPixelShader: false
    UseInVertexShader: true
    Value:
      w: 0
      x: 0
      y: 0
      z: 0
  - Name: ImageScale
    UseInPixelShader: false
    UseInVertexShader: true
    Value:
      w: 1
      x: 5
      y: 5
      z: 0
  - Name: Displacement
    UseInPixelShader: false
    UseInVertexShader: true
    Value:
      w: 0
      x: 0
      y: 0
      z: 0
Textures:
  - SamplerName: BaseColor
    TextureName: LavaTexture_BaseColor
    UseInPixelShader: false
    UseInVertexShader: false
  - SamplerName: Displacement
    TextureName: LavaTexture_Displacement
    UseInPixelShader: false
    UseInVertexShader: true
VertexShader: D:/Projects/CMake/Sandbox/Sandbox/Assets/Test/TestMaterial.vs
