{
	"Nodes" : [{
		"Connections" : [{
			"Source" : "Color",
			"Target" : "Multiply/Result"
		}],
		"Data" : {
			"Function" : "FragmentShader"
		},
		"Identifier" : "FragmentShader",
		"Position" : {
			"W" : 0.000000,
			"X" : 360.000000,
			"Y" : 280.000000,
			"Z" : 0.000000
		}
	}, {
		"Connections" : [{
			"Source" : "Position",
			"Target" : "Transform/Vector"
		}],
		"Data" : {
			"Function" : "VertexShader"
		},
		"Identifier" : "VertexShader",
		"Position" : {
			"W" : 0.000000,
			"X" : 760.000000,
			"Y" : 0.000000,
			"Z" : 0.000000
		}
	}, {
		"Data" : {
			"Function" : "Position"
		},
		"Identifier" : "Position",
		"Position" : {
			"W" : 0.000000,
			"X" : 260.000000,
			"Y" : 60.000000,
			"Z" : 0.000000
		}
	}, {
		"Data" : {
			"Function" : "Normal"
		},
		"Identifier" : "Normal",
		"Position" : {
			"W" : 0.000000,
			"X" : 140.000000,
			"Y" : 120.000000,
			"Z" : 0.000000
		}
	}, {
		"Connections" : [{
			"Source" : "A",
			"Target" : "Normal/Value"
		}, {
			"Source" : "B",
			"Target" : "DisplacementMap/Color"
		}],
		"Data" : {
			"Function" : "Multiply"
		},
		"Identifier" : "Multiply2",
		"Position" : {
			"W" : 0.000000,
			"X" : 220.000000,
			"Y" : 140.000000,
			"Z" : 0.000000
		}
	}, {
		"Connections" : [{
			"Source" : "UV",
			"Target" : "UV/Value"
		}],
		"Data" : {
			"Function" : "DisplacementMap"
		},
		"Identifier" : "DisplacementMap",
		"Position" : {
			"W" : 0.000000,
			"X" : 80.000000,
			"Y" : 200.000000,
			"Z" : 0.000000
		}
	}, {
		"Connections" : [{
			"Source" : "UV",
			"Target" : "UV/Value"
		}],
		"Data" : {
			"Function" : "AmbientOcclusionMap"
		},
		"Identifier" : "AmbientOcclusionMap",
		"Position" : {
			"W" : 0.000000,
			"X" : 80.000000,
			"Y" : 360.000000,
			"Z" : 0.000000
		}
	}, {
		"Data" : {
			"Function" : "UV"
		},
		"Identifier" : "UV",
		"Position" : {
			"W" : 0.000000,
			"X" : 0.000000,
			"Y" : 280.000000,
			"Z" : 0.000000
		}
	}, {
		"Connections" : [{
			"Source" : "UV",
			"Target" : "UV/Value"
		}],
		"Data" : {
			"Function" : "ColorMap"
		},
		"Identifier" : "ColorMap",
		"Position" : {
			"W" : 0.000000,
			"X" : 80.000000,
			"Y" : 280.000000,
			"Z" : 0.000000
		}
	}, {
		"Connections" : [{
			"Source" : "B",
			"Target" : "Multiply2/Result"
		}, {
			"Source" : "A",
			"Target" : "Position/Value"
		}],
		"Data" : {
			"Function" : "Add"
		},
		"Identifier" : "Add",
		"Position" : {
			"W" : 0.000000,
			"X" : 340.000000,
			"Y" : 80.000000,
			"Z" : 0.000000
		}
	}, {
		"Data" : {
			"Function" : "ModelViewProjectionMatrix"
		},
		"Identifier" : "ModelViewProjectionMatrix",
		"Position" : {
			"W" : 0.000000,
			"X" : 420.000000,
			"Y" : 0.000000,
			"Z" : 0.000000
		}
	}, {
		"Connections" : [{
			"Source" : "Vector",
			"Target" : "Hot-Fix :(/Vector4"
		}, {
			"Source" : "Matrix",
			"Target" : "ModelViewProjectionMatrix/Value"
		}],
		"Data" : {
			"Function" : "Transform"
		},
		"Identifier" : "Transform",
		"Position" : {
			"W" : 0.000000,
			"X" : 620.000000,
			"Y" : 0.000000,
			"Z" : 0.000000
		}
	}, {
		"Connections" : [{
			"Source" : "B",
			"Target" : "AmbientOcclusionMap/Color"
		}, {
			"Source" : "A",
			"Target" : "ColorMap/Color"
		}],
		"Data" : {
			"Function" : "Multiply"
		},
		"Identifier" : "Multiply",
		"Position" : {
			"W" : 0.000000,
			"X" : 240.000000,
			"Y" : 280.000000,
			"Z" : 0.000000
		}
	}, {
		"Connections" : [{
			"Source" : "Vector3",
			"Target" : "Add/Result"
		}],
		"Data" : {
			"Function" : "Hot-Fix :("
		},
		"Identifier" : "Hot-Fix :(",
		"Position" : {
			"W" : 0.000000,
			"X" : 460.000000,
			"Y" : 80.000000,
			"Z" : 0.000000
		}
	}],
	"Type" : "Material"
}