Type: Class
Attributes:
  - Structure
BaseType: UI.Layout
Functions:
  - InputParameters:
      - Copy: false
        Name: Entity
        Type: ECS.Entity
        Writable: true
    Name: OnPrePass
    OutputParameters:
      - Copy: false
        Name: Success
        Type: bool
        Writable: false
Graphs:
  Function.OnPrePass:
    Nodes:
      - ID: Input
        Name: Input
      - ID: Output
        Name: Output
Namespace: UI
